image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.2"
  SDK_TOOLS: "4333796" # from https://developer.android.com/studio/#command-tools
  EMULATOR_VERSION: "24"

before_script:
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${SDK_TOOLS}.zip
  - unzip -q android-sdk.zip -d android-sdk-linux
  - rm android-sdk.zip

  - mkdir android-sdk-linux/licenses
  - printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > android-sdk-linux/licenses/android-sdk-license
  - printf "84831b9409646a918e30573bab4c9c91346d8abd" > android-sdk-linux/licenses/android-sdk-preview-license
  - android-sdk-linux/tools/bin/sdkmanager --update > update.log
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" "extras;google;m2repository" "extras;android;m2repository" > installPlatform.log

  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export ADB_HOME=ANDROID_HOME/platform-tools
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew

stages:
#  - build
  - test
  - quality_assurance

#build_job:
#  stage: build
#  script:
#    - ./gradlew clean build
#  artifacts:
#    paths:
#    - weather-logger/build/outputs/

unit_tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - weather-logger/build/reports/tests/

instrumentation_tests:
  stage: test
  script:
    - cd $PWD/android-sdk-linux/platform-tools/
    - emulator -avd testAVD -no-audio -no-window &
    - ./adb wait-for-device #./ci/android-wait-for-emulator.sh
    - ./adb devices
    - ./adb shell settings put global window_animation_scale 0 &
    - ./adb shell settings put global transition_animation_scale 0 &
    - ./adb shell settings put global animator_duration_scale 0 &
    - ./adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest
    - ./ci/stop-emulators.sh
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - weather-logger/build/reports/androidTests/connected/

static_analysis:
  stage: quality_assurance
  script:
    - ./gradlew lint
    - ./gradlew checkstyle
    - ./gradlew pmd
    - ./gradlew findbugs
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - weather-logger/build/reports/
