image: mirjalal/gitlab-ci-docker-image

services:
  - docker:dind

#build:
#  script:
#    - docker build -t mirjalal/gitlab-ci-docker-image .
#    - docker push mirjalal/gitlab-ci-docker-image

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.2"
  ANDROID_SDK_TOOLS: "4333796" # from https://developer.android.com/studio/#command-tools
 # GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - echo "ad8ad258047a00e2ee528be5b1a8a18bab7c4367" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
  - cat $ANDROID_HOME/licenses/*

stages:
#  - build
  - test
#  - quality_assurance

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

#building:
#  stage: build
#  script:
#    - ./gradlew build

#unitTests:
#  stage: test
#  script:
#    - ./gradlew test

instrumentedTests:
  stage: test
  script:
    - env
    - curl -s https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator > android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
    - $ANDROID_HOME/tools/bin/sdkmanager --update > update.log
    - $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "emulator" "system-images;android-25;google_apis;armeabi-v7a"  > installEmulator.log
    - $ANDROID_HOME/platform-tools/adb start-server
    - echo no | $ANDROID_HOME/tools/bin/avdmanager -v create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
    - $ANDROID_HOME/emulator/emulator -avd test -memory 512 -no-boot-anim -no-snapshot-save -no-audio -no-window -gpu off -debug -all
    - ./android-wait-for-emulator
    # Turn off animations
    - $ANDROID_HOME/platform-tools/adb shell settings put global window_animation_scale 0 &
    - $ANDROID_HOME/platform-tools/adb shell settings put global transition_animation_scale 0 &
    - $ANDROID_HOME/platform-tools/adb shell settings put global animator_duration_scale 0 &
    - $ANDROID_HOME/platform-tools/adb shell input keyevent 82
    - ./gradlew connectedAndroidTest
    - $ANDROID_HOME/platform-tools/adb emu kill

#staticAnalysis:
#  stage: quality_assurance
#  script:
#    - ./gradlew lint
#    - ./gradlew checkstyle
#    - ./gradlew pmd
#    - ./gradlew findbugs