version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "weather-logger/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :weather-logger:clean
            ./gradlew :weather-logger:build
      - run:
          name: Run Unit Tests
          command: |
            ./gradlew test
      - run:
          name: Run Unit Tests
          command: |
            ./gradlew connectedAndroidTest
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "weather-logger/build.gradle" }}
      - store_artifacts:
          path: weather-logger/build/reports
          destination: reports
